FORMAT: 1A
HOST: http://bla.com

# muh stuff
Gist Fox API is a **pastes service** similar to (GitHub's Gist)[http://gist.github.com]

# Group addressbook

# contacts [/addressbook/contacts/{id}]
handle contacts

## Search all contacts [GET]
+ Response 200 (application/hal+json)

+ request this is a test (application/hal+json)

        {
            "message": "test"
        }
+ Parameters
    + id (optional, number) ... Maximum number of posts to retrieve
    
+ Response 200 (application/hal+json)


## Create a single contact [POST]
+ Response 200 (application/hal+json)

## Update a single contact [PUT]
+ Response 200 (application/hal+json)

## Delete a single contact [DELETE]
+ Response 200 (application/hal+json)

# street addresses [/addressbook/streetaddresses]
handle street addresses

## Search all street addresses [GET]
+ Response 200 (application/hal+json)

## Update a single street addresses [PUT]
+ Response 200 (application/hal+json)

## Delete a single street addresses [DELETE]
+ Response 200 (application/hal+json)

# phone numbers [/addressbook/phonenumbers]
handle phone numbers

## Search all phone numbers [GET]
+ Response 200 (application/hal+json)

## Update a single phone numbers [PUT]
+ Response 200 (application/hal+json)

## Delete a single phone numbers [DELETE]
+ Response 200 (application/hal+json)

# bulk import contacts [/addressbook/import]
import contacts in bulk

## Upload dataset of new contacts [POST]
+ Response 200 (application/hal+json)

## Delete multiple contacts [DELETE]
+ Response 200 (application/hal+json)

# export contacts [/addressbook/export]
export contacts

## pass in query object [POST]
+ Response 200 (application/hal+json)

# Group planning

# projects [/planning/projects]
handle projects

## Search all projects [GET]
+ Response 200 (application/hal+json)

## Create a single project [POST]
+ Response 200 (application/hal+json)

## Update a single project [PUT]
+ Response 200 (application/hal+json)

## Delete a single project [DELETE]
+ Response 200 (application/hal+json)

# milestones [/planning/milestones]
handle milestones

## Search all milestones [GET]
+ Response 200 (application/hal+json)

## Create a single milestone [POST]
+ Response 200 (application/hal+json)

## Update a single milestone [PUT]
+ Response 200 (application/hal+json)

## Delete a single milestone [DELETE]
+ Response 200 (application/hal+json)

# tasks [/planning/tasks]
handle tasks

## Search all tasks [GET]
+ Response 200 (application/hal+json)

## Create a single task [POST]
+ Response 200 (application/hal+json)

## Update a single task [PUT]
+ Response 200 (application/hal+json)

## Delete a single task [DELETE]
+ Response 200 (application/hal+json)

# taskentries [/planning/tasksentries]
handle taskentries

## Search all taskentries [GET]
+ Response 200 (application/hal+json)

## Create a single taskentry [POST]
+ Response 200 (application/hal+json)

## Update a single taskentry [PUT]
+ Response 200 (application/hal+json)

## Delete a single taskentry [DELETE]
+ Response 200 (application/hal+json)

# Group access

# users [/access/users]
handle users

## Search all users [GET]
+ Response 200 (application/hal+json)

## Create a single user [POST]
+ Response 200 (application/hal+json)

## Update a single user [PUT]
+ Response 200 (application/hal+json)

## Delete a single user [DELETE]
+ Response 200 (application/hal+json)

# usergroups [/access/usergroups]
handle usergroups

## Search all usergroups [GET]
+ Response 200 (application/hal+json)

## Create a single usergroup [POST]
+ Response 200 (application/hal+json)

## Update a single usergroup [PUT]
+ Response 200 (application/hal+json)

## Delete a single usergroup [DELETE]
+ Response 200 (application/hal+json)

# accounts [/access/accounts]
handle accounts

## Search all accounts [GET]
+ Response 200 (application/hal+json)

## Create a single account [POST]
+ Response 200 (application/hal+json)

## Update a single account [PUT]
+ Response 200 (application/hal+json)

## Delete a single account [DELETE]
+ Response 200 (application/hal+json)

# authenticate [/access/authenticate]

## pass username/password to login to the system [POST]
+ Response 200 (application/hal+json)

## pass an auth token to logoff the system [DELETE]
+ Response 200 (application/hal+json)

# authorize [/access/authorize]

## pass subject/object to check if user has access to that object [POST]
+ Response 200 (application/hal+json)



## users [/accesssdf/users]
bla 123

## Search users [GET]

+ Response 200 (application/hal+json)
    + Headers
    + Body
    
            {}

## Create user [POST]

+ Response 200 (application/hal+json)
    + Headers
    + Body
    
            {}

## Update user [PATCH]

+ Response 200 (application/hal+json)
    + Headers
    + Body
    
            {}


## Delete user [DELETE]

+ Response 200 (application/hal+json)
    + Headers
    + Body
    
            {}

## users [/access/]
bla 123

## Search users [GET]

+ Response 200 (application/hal+json)
    + Headers
    + Body
    
            {}

## Create user [POST]

+ Response 200 (application/hal+json)
    + Headers
    + Body
    
            {}

## Update user [PATCH]

+ Response 200 (application/hal+json)
    + Headers
    + Body
    
            {}


## Delete user [DELETE]

+ Response 200 (application/hal+json)
    + Headers
    + Body
    
            {}

## fetch a single account [/accounts/{id}]
Gist Fox API entry point.

This resource does not have any attributes. Instead it offers the initial API affordances in the form of the HTTP Link header and HAL links.
The Gist resource has the following attributes:

+ Parameters

    + id (string) ... ID of the gist in the form of a hash

## Retrieve Entry Point [GET]

+ Response 200 (application/hal+json)
    + Headers
    
            Link: <http:/api.gistfox.com/>;rel="self",<http:/api.gistfox.com/gists>;rel="gists"

    + Body

            {
                "_links": {
                    "self": { "href": "/" },
                    "gists": { "href": "/gists?{since}", "templated": true }
                }
            }
            
# Group Gist 123
Gist-related resources of *Gist Fox API*.

## Gist [/gists/{id}]
A single Gist object. The Gist resource is the central resource in the Gist Fox API. It represents one paste - a single text note.

The Gist resource has the following attributes:

- id
- created_at
- description
- content

The states *id* and *created_at* are assigned by the Gist Fox API at the moment of creation.


+ Parameters
    + id (string) ... ID of the Gist in the form of a hash.

+ Model (application/hal+json)

    HAL+JSON representation of Gist Resource. In addition to representing its state in the JSON form it offers affordances in the form of the HTTP Link header and HAL links.

    + Headers

            Link: <http:/api.gistfox.com/gists/42>;rel="self", <http:/api.gistfox.com/gists/42/star>;rel="star"

    + Body

            {
                "_links": {
                    "self": { "href": "/gists/42" },
                    "star": { "href": "/gists/42/star" },
                },
                "id": "42",
                "created_at": "2014-04-14T02:15:15Z",
                "description": "Description of Gist",
                "content": "String contents"
            }

### Retrieve a Single Gist [GET]
+ Response 200

    [Gist][]
    
### Edit a Gist [PATCH]
To update a Gist send a JSON with updated value for one or more of the Gist resource attributes. All attributes values (states) from the previous version of this Gist are carried over by default if not included in the hash.

+ Request (application/json)

        {
            "content": "Updated file contents"
        }

+ Response 200

    [Gist][]

### Delete a Gist [DELETE]
+ Response 204

## Gists Collection [/gists{?since}]
Collection of all Gists.

The Gist Collection resource has the following attribute:

- total

In addition it **embeds** *Gist Resources* in the Gist Fox API.


+ Model (application/hal+json)

    HAL+JSON representation of Gist Collection Resource. The Gist resources in collections are embedded. Note the embedded Gists resource are incomplete representations of the Gist in question. Use the respective Gist link to retrieve its full representation.

    + Headers

            Link: <http:/api.gistfox.com/gists>;rel="self"

    + Body

            {
                "_links": {
                    "self": { "href": "/gists" }
                },
                "_embedded": {
                    "gists": [
                        {
                            "_links" : {
                                "self": { "href": "/gists/42" }
                            },
                            "id": "42",
                            "created_at": "2014-04-14T02:15:15Z",
                            "description": "Description of Gist"
                        }
                    ]
                },
                "total": 1
            }

### List All Gists [GET]
+ Parameters
    + since (optional, string) ... Timestamp in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ` Only Gists updated at or after this time are returned.

+ Response 200

    [Gists Collection][]

### Create a Gist [POST]
To create a new Gist simply provide a JSON hash of the *description* and *content* attributes for the new Gist.

+ Request (application/json)

        {
            "description": "Description of Gist",
            "content": "String content"
        }

+ Response 201

    [Gist][]

## Star [/gists/{id}/star]
Star resource represents a Gist starred status.

The Star resource has the following attribute:

- starred


+ Parameters

    + id (string) ... ID of the gist in the form of a hash

+ Model (application/hal+json)

    HAL+JSON representation of Star Resource.

    + Headers

            Link: <http:/api.gistfox.com/gists/42/star>;rel="self"

    + Body

            {
                "_links": {
                    "self": { "href": "/gists/42/star" },
                },
                "starred": true
            }

### Star a Gist [PUT]
+ Response 204

### Unstar a Gist [DELETE]
+ Response 204

### Check if a Gist is Starred [GET]
+ Response 200

    [Star][]